enum ActionType {
  MARK_DAY = "MARK_DAY/MARK_DAY-MARK_DAY",
  IS_MARK_DAY = "MARK_DAY/IS_MARK_DAY-IS_MARK_DAY",
  SET_IS_MARK = "SET_IS_MARK/IS_MARK_DAY-SET_IS_MARK",
  SET_SELECTED_DAY = "SET_IS_MARK/SET_SELECTED_DAY-SET_SELECTED_DAY",
  GET_MARKING_MODE = "GET_MARKING_MODE/GET_MARKING_MODE-SET_SELECTED_DAY",
  GET_MARK_COLOR = "GET_MARKING_MODE/GET_MARK_COLOR-GET_MARK_COLOR",
  SET_MARK_COLOR = "GET_MARKING_MODE/SET_MARK_COLOR-SET_MARK_COLOR",
  LOAD_CALENDAR = "GET_MARKING_MODE/LOAD_CALENDAR-LOAD_CALENDAR",
  SAVE_CALENDAR = "SAVE_CALENDAR/SAVE_CALENDAR-SAVE_CALENDAR",


}

export { ActionType }
